name: ssh-into-aws-ec2

on:
  push:
    branches: ["main"]

env:
  REMOTE_HOST: ${{ secrets.HOST }}
  REMOTE_USER: ${{ secrets.USERNAME }}

permissions:
  contents: read
  id-token: write

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #      - name: Build the frontend application
      #        run: |
      #          npm install
      #          unset CI
      #         npm run build
      - name: deploy frontend build files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.KEY }}
          local_path: "./*"
          remote_path: "/var/www/fend"
          sftpArgs: "-o ConnectTimeout=50"
